config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: "users/sessions",
  }
  root 'top#index'
  resources :users, only: [:index, :show]
  resources :food_preps do
    collection do
      get 'search'
    end
  end  
  resources :labels
  resources :select_food_preps do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  resources :groups do
    resources :group_users
  end
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/admin_guest_sign_in', to: 'users/sessions#admin_guest_sign_in'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :select_food_prep
  belongs_to :user
  validates :content, presence: true
end

app/models/food_prep.rb
class FoodPrep < ApplicationRecord
  validates :name, presence: true
  validates :ingredient, presence: true
  validates :group_id, presence: true
  has_many :food_prep_labels, dependent: :destroy
  has_many :labels, through: :food_prep_labels, source: :label
  has_many :select_food_preps, dependent: :destroy
  belongs_to :group
end

app/models/food_prep_label.rb
class FoodPrepLabel < ApplicationRecord
  belongs_to :food_prep
  belongs_to :label
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true, length: { maximum: 20 }

  belongs_to :owner, class_name: 'User'
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users, source: :user
  has_many :food_preps, dependent: :destroy
  has_many :select_food_preps, dependent: :destroy

  def invite_member(user)
    group_users.create(user: user)
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/label.rb
class Label < ApplicationRecord
  validates :name, presence: true
  has_many :food_prep_labels, dependent: :destroy
  has_many :food_preps, through: :food_prep_labels, source: :food_prep
end

app/models/select_food_prep.rb
class SelectFoodPrep < ApplicationRecord
  validates :group_id, presence: true
  validates :to_do_at, presence: true
  belongs_to :user
  belongs_to :food_prep
  belongs_to :group
  has_many :comments, dependent: :destroy

  def start_time
    self.to_do_at
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, length: { minimum: 6 }
  has_many :select_food_preps, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users, source: :group

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guest"
      user.admin = false
    end
  end

  def self.guest_admin
    find_or_create_by!(email: 'admin_guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "admin_guest"
      user.admin = true
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @group = Group.new
  end

  def edit
  end

  def create
    @group = current_user.groups.build(group_params)
    @group.owner = current_user
    if @group.save
      @group.invite_member(@group.owner)
      redirect_to group_url(@group), notice: "グループを作成しました"
    else
      flash.now[:notice] = "グループの作成に失敗しました"
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to @group, notice: "グループを編集しました"
    else
      flash.now[:error]
      render :edit
    end  
  end

  def destroy
    @group.destroy
    redirect_to user_path(current_user.id), notice: "グループを削除しました"
  end
end

private

def set_group
  @group = Group.find(params[:id])
end

def group_params
  params.require(:group).permit(:name)
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: [:edit, :update, :destroy]

  def index
    @labels = Label.all
  end

  def new
    @label = Label.new
  end

  def edit
  end

  def create
    @label = Label.new(label_params)
    if @label.save
      redirect_to labels_path, notice: 'ラベルを登録しました'
    else
      render :new
    end
  end

  def update
    if @label.update(label_params)
      redirect_to labels_path, notice: 'ラベルを更新しました'
    else
      render :edit
    end
  end

  def destroy
    @label.destroy
    redirect_to labels_path, notice: 'ラベルを削除しました'
  end

  private

  def set_label
    @label = Label.find(params[:id])
  end

  def label_params
    params.require(:label).permit(:name)
  end
end

app/controllers/select_food_preps_controller.rb
class SelectFoodPrepsController < ApplicationController
  def index
    @select_food_preps = SelectFoodPrep.all
    @group_select_food_preps = @select_food_preps.where(group_id: current_user.group_ids)
  end

  def show
    @select_food_prep = SelectFoodPrep.find(params[:id])
    @comments = @select_food_prep.comments
    @comment = @select_food_prep.comments.build
  end

  def new
    @select_food_prep = SelectFoodPrep.new
    @groups = GroupUser.where(user_id: current_user.id)
  end

  def create
    @select_food_prep = SelectFoodPrep.new(select_food_prep_params)
    @select_food_prep.user_id = current_user.id
    @select_food_prep.food_prep_id = select_food_prep_params[:food_prep_id]
    if @select_food_prep.save
      redirect_to select_food_preps_path, notice: '仕込みを選択しました'
    else
      @groups = GroupUser.where(user_id: current_user.id)
      render :new
    end
  end

  def destroy
    @select_food_prep = SelectFoodPrep.find(params[:id])
    @select_food_prep.destroy
    redirect_to select_food_preps_path, notice: '仕込みを削除しました'
  end

  private

  def select_food_prep_params
    params.require(:select_food_prep).permit(:user_id, :food_prep_id, :to_do_at, :group_id)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @groups = Group.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/food_preps_helper.rb
module FoodPrepsHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/select_food_preps_helper.rb
module SelectFoodPrepsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/select_food_preps/index.html.erb
<div class="container">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
        <div class="card">
          <div class="card-body">
            <h1>本日の仕込み</h1>
            <h3><%= Date.current.strftime('%Y年 %m月 %d日') %></h3>
            <%= link_to " 新しく仕込みを選択する", new_select_food_prep_path, class: "bi bi-plus-circle-fill btn btn-primary"%>
          </div>
        </div>
      </div>
    </div>        
  </div>
  <br>
  <br>
  <table class = "table">
    <thead class="border-top">
      <tr>
        <th>実行済み</th>
        <th>仕込み項目名</th>
        <th>使用食材</th>
        <th>実施日</th>
        <th>担当者</th>
      </tr>
    </thead>
    <tbody>
      <% @group_select_food_preps.each do |select_food_prep| %>
        <% if select_food_prep.to_do_at == Date.current %>
          <tr class="border-bottom">
            <td><%= check_box_tag :executed %>
            <td><%= select_food_prep.food_prep.name %></td>
            <td><%= select_food_prep.food_prep.ingredient %></td>
            <td><%= select_food_prep.to_do_at %></td>
            <td><%= select_food_prep.user.name %></td>
            <td><%= link_to '詳細', select_food_prep_path(select_food_prep), method: :get, class: "bi bi-file-text-fill btn btn-outline-success btn-sm" %></td>
            <td><%= link_to '削除', select_food_prep_path(select_food_prep), method: :delete, data: { confirm: "本当に削除しますか？" }, class: "bi bi-trash3-fill btn btn-outline-danger btn-sm"  %></td>
          </tr>
        <% end %>
      <% end %>  
    </tbody>  
  </table>
  <h4 class = 'bi bi-calendar3 border-bottom border-dark'>仕込みカレンダー</h4>
  <div class = "simple_calendar">
    <%= month_calendar events: @group_select_food_preps do |date, food_preps| %>
      <%= date.day %>

      <% food_preps.each do |food_prep| %>
        <div>
          <%= link_to food_prep.food_prep.name, food_prep %>
        </div>
      <% end %> 
    <% end %>
  </div>  
</div>  

app/views/select_food_preps/new.html.erb
<%= form_with(model: @select_food_prep, local: true) do |form| %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8">
      <div class="card">
        <div class="card-body"> 
        <h1>仕込み選択</h1>
        <p>仕込みの予定を追加します</p><br>
          <% if @select_food_prep.errors.any? %>
            <div id="error_explanation">
              <h3><%= pluralize(@select_food_prep.errors.count, "件の") %> エラーがあります</h3>
                <% @select_food_prep.errors.full_messages.each do |message| %>
                  <%= message %><br>
                <% end %>
            </div>
          <% end %>
          <br>
          <div class="form-group">
            <%= form.label "仕込み項目名" %><br>
            <%= form.select :food_prep_id, FoodPrep.where(group_id: current_user.groups.ids).pluck(:name, :id), { include_blank: '選択してください'}%>
          </div>
          <div class="form-group">
            <%= form.label "実施日" %><br>
            <%= form.date_field :to_do_at %>
          </div>
          <div class="field">
              <%= form.label "グループ名" %>
            <% @groups.each do |group| %>
              <%= form.check_box :group_id, { multiple: false, include_hidden: false }, group[:group_id] %>
              <%= group.group.name %>
            <% end %>
          </div>
          <br>
          <div class="actions">
            <%= form.submit "予定に追加する", class: "btn btn btn-info" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<%= link_to '戻る', select_food_preps_path, class: "bi bi-skip-backward-fill btn btn-sm btn-primary"  %>        
<% end %>

app/views/select_food_preps/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8">
      <div class="card">
        <div class="card-body border border-dark">
          <h2 class="bi bi-info-circle">仕込み予定詳細</h2><br>
            <div class="card">
              <div class="card-body">
                <p class="text-center border-bottom">
                  <strong><%= '仕込み項目名' %>:</strong>
                  <%= @select_food_prep.food_prep.name %>
                </p>
                <p class="text-center border-bottom">
                  <strong>使用食材:</strong>
                  <%= @select_food_prep.food_prep.ingredient %>
                </p>
                <p class="text-center border-bottom">
                  <strong>実施日:</strong>
                  <%= @select_food_prep.to_do_at %>
                </p>
                <p class="text-center border-bottom">
                  <strong>担当者:</strong>
                  <%= @select_food_prep.user.name %>
                </p>
              </div>  
            </div>
          <div id="comments_area">
            <%= render partial: 'comments/index', locals: { comments: @comments, select_food_prep: @select_food_prep } %>
          </div>
          <div id="form_area">
            <%= render partial: 'comments/form', locals: { comment: @comment, select_food_prep: @select_food_prep } %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<%= link_to ' 戻る', select_food_preps_path, class: "btn btn-primary btn-sm bi bi-skip-backward-fill" %>