config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: "users/sessions",
  }
  root 'top#index'
  resources :users, only: [:index, :show]
  resources :food_preps do
    collection do
      get 'search'
    end
  end  
  resources :labels
  resources :select_food_preps do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  resources :groups do
    resources :group_users
  end
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/admin_guest_sign_in', to: 'users/sessions#admin_guest_sign_in'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.try(:admin?)
      can :access, :rails_admin
      can :manage, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :select_food_prep
  belongs_to :user
  validates :content, presence: true
end

app/models/food_prep.rb
class FoodPrep < ApplicationRecord
  validates :name, presence: true
  validates :ingredient, presence: true
  validates :group_id, presence: true
  has_many :food_prep_labels, dependent: :destroy
  has_many :labels, through: :food_prep_labels, source: :label
  has_many :select_food_preps, dependent: :destroy
  belongs_to :group
end

app/models/food_prep_label.rb
class FoodPrepLabel < ApplicationRecord
  belongs_to :food_prep
  belongs_to :label
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true, length: { maximum: 20 }

  belongs_to :owner, class_name: 'User'
  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users, source: :user
  has_many :food_preps, dependent: :destroy
  has_many :select_food_preps, dependent: :destroy

  def invite_member(user)
    group_users.create(user: user)
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/label.rb
class Label < ApplicationRecord
  validates :name, presence: true
  has_many :food_prep_labels, dependent: :destroy
  has_many :food_preps, through: :food_prep_labels, source: :food_prep
end

app/models/select_food_prep.rb
class SelectFoodPrep < ApplicationRecord
  validates :group_id, presence: true
  validates :to_do_at, presence: true
  belongs_to :user
  belongs_to :food_prep
  belongs_to :group
  has_many :comments, dependent: :destroy

  def start_time
    self.to_do_at
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :password, length: { minimum: 6 }
  has_many :select_food_preps, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :group_users, dependent: :destroy
  has_many :groups, through: :group_users, source: :group

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guest"
      user.admin = false
    end
  end

  def self.guest_admin
    find_or_create_by!(email: 'admin_guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "admin_guest"
      user.admin = true
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_select_food_prep
  
  def edit
    @comment = @select_food_prep.comments.find(params[:id])
    respond_to do |format|
      flash.now[:notice] = 'コメントの編集中'
      format.html { redirect_to @select_food_prep }
      format.js { render :edit }
    end
  end

  def create
    @comment = @select_food_prep.comments.build(comment_params)
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        flash.now[:notice] = 'コメントが投稿されました'
        format.js { render :index }
      else
        flash.now[:notice] = 'コメントの投稿に失敗しました'
        format.js { render :index }
      end
    end
  end  

  def update
    @comment = @select_food_prep.comments.find(params[:id])
    respond_to do |format|
      if @comment.update(comment_params)
        flash.now[:notice] = 'コメントが編集されました'
        format.js { render :index }
      else
        flash.now[:notice] = 'コメントの編集に失敗しました'
        format.js { render :index }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
      @comment.destroy!
      respond_to do |format|
        flash.now[:notice] = 'コメントが削除されました'
        format.js { render :index }
      end
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :select_food_prep_id, :user_id)
  end

  def set_select_food_prep
    @select_food_prep = SelectFoodPrep.find(params[:select_food_prep_id])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @group = Group.new
  end

  def edit
  end

  def create
    @group = current_user.groups.build(group_params)
    @group.owner = current_user
    if @group.save
      @group.invite_member(@group.owner)
      redirect_to group_url(@group), notice: "グループを作成しました"
    else
      flash.now[:notice] = "グループの作成に失敗しました"
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to @group, notice: "グループを編集しました"
    else
      flash.now[:error]
      render :edit
    end  
  end

  def destroy
    @group.destroy
    redirect_to user_path(current_user.id), notice: "グループを削除しました"
  end
end

private

def set_group
  @group = Group.find(params[:id])
end

def group_params
  params.require(:group).permit(:name)
end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController
  before_action :set_label, only: [:edit, :update, :destroy]

  def index
    @labels = Label.all
  end

  def new
    @label = Label.new
  end

  def edit
  end

  def create
    @label = Label.new(label_params)
    if @label.save
      redirect_to labels_path, notice: 'ラベルを登録しました'
    else
      render :new
    end
  end

  def update
    if @label.update(label_params)
      redirect_to labels_path, notice: 'ラベルを更新しました'
    else
      render :edit
    end
  end

  def destroy
    @label.destroy
    redirect_to labels_path, notice: 'ラベルを削除しました'
  end

  private

  def set_label
    @label = Label.find(params[:id])
  end

  def label_params
    params.require(:label).permit(:name)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @groups = Group.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/food_preps_helper.rb
module FoodPrepsHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/labels_helper.rb
module LabelsHelper
end

app/helpers/select_food_preps_helper.rb
module SelectFoodPrepsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_edit.html.erb
<%= render 'layouts/flash' %>
<div class="comment_edit_form">
  <%= form_with(model: [select_food_prep, comment], local: false) do |form| %>
    <div class="form-group">
      <%= form.text_area "コメント内容", id: "comment_content_#{select_food_prep.id}", class: "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit "編集", class: "btn btn-info"  %>
    </div>
    <%= link_to :back do %>
      戻る
    <% end %>
  <% end %>
</div>

app/views/comments/_form.html.erb
<div class="comment-form">
  <%= form_with(model: [select_food_prep, comment], local: false) do |form| %>
    <div class="form-group">
      <%= form.label :content, "コメント内容" %>
      <%= form.text_area :content, class: "form-control" %>
    </div>

    <div class="actions">
      <%= form.submit "コメントを投稿", class: "btn btn-info"  %>
    </div>
  <% end %>
</div>

app/views/comments/_index.html.erb
<%= render 'layouts/flash' %>
<% comments.order(created_at: :asc).each do |comment| %>
  <div id ="this_comment_<%= comment.id %>">
    <strong class="border-bottom border-dark">コメント内容</strong>
    <span><%= simple_format(comment.content) %></span>
    <small>投稿者:<%= comment.user.name %></small><br>
    <small>日時:<%= comment.created_at.strftime("%Y-%m-%d %H:%M") %></small>
    <span><%= link_to '', edit_select_food_prep_comment_path(select_food_prep, comment), remote: true, class: "btn-sm bi bi-pencil-fill btn btn-success btn-sm" %></span>
    <span><%= link_to '', select_food_prep_comment_path(comment.select_food_prep_id, comment.id), data: { confirm: "本当に削除しますか?"}, method: :delete, remote: true, class: "btn btn-danger btn-sm bi bi-trash3-fill" %></span>
  </div>
<% end %>

app/views/comments/edit.js.erb
$('.alert').remove();
$("#this_comment_<%= @comment.id %>").replaceWith("<%= j(render 'comments/edit', { select_food_prep: @select_food_prep, comment: @comment }) %>");

app/views/comments/index.js.erb
$("#comments_area").html("<%= j(render 'comments/index', { comments: @comment.select_food_prep.comments, select_food_prep: @comment.select_food_prep }) %>")
$("textarea").val('')

app/views/groups/edit.html.erb
<%= form_with(model: @group, local: true) do |f| %>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-10">
        <div class="card">
          <div class="card-body">
            <h1>グループ編集</h1>
            <% if @group.errors.any? %>
              <div id="error_explanation">
                <h4><%= pluralize(@group.errors.count, "件の") %> エラーがあります</h4>
                  <% @group.errors.full_messages.each do |message| %>
                    <%= message %><br>
                  <% end %>
              </div>
            <% end %>
            <div class="form-group">
              <p><%= f.label 'グループ名' %></p>
              <p><%= f.text_field :name, class: "form-control" %></p>

              <div class="button">  
                <%= f.submit '編集する', class: "btn btn-info" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>        
  </div>
<br>      
<%= link_to "戻る", user_path(current_user.id), id: "back", class: "bi bi-skip-backward-fill btn btn-primary btn-sm" %>  
<% end %>

app/views/groups/new.html.erb
<%= form_with(model: @group, local: true) do |f| %>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
        <div class="card">
          <div class="card-body">
            <h2>グループ作成</h2>
            <% if @group.errors.any? %>
              <div id="error_explanation">
                <h4><%= pluralize(@group.errors.count, "件の") %> エラーがあります</h4>
                  <% @group.errors.full_messages.each do |message| %>
                    <%= message %><br>
                  <% end %>
              </div>
            <% end %>
            <div class="form-group">
              <p><%= f.label 'グループ名' %></p>
              <p><%= f.text_field :name, placeholder: "レストラン:cucina", class: "form-control" %></p>
            </div>
            <div class="button">  
              <%= f.submit '作成する', class: "btn btn-info" %>
            </div>  
          </div>
        </div>
      </div>
    </div>        
  </div>  
<% end %>
<br>
<%= link_to "戻る", user_path(current_user.id), id: "back", class: "bi bi-skip-backward-fill btn btn-primary btn-sm" %>  

app/views/groups/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8">
      <div class="card">
        <div class="card-body">
          <h2 class="border-bottom">グループ詳細</h2><br>
            <h4 class="bi bi-bookmark-check-fill">グループ名</h4>
            <p class="border-bottom"><%= @group.name %></p>
            <h4 class="bi bi-person-check-fill">オーナー</h4>
            <p class="border-bottom"><%= @group.owner.name %>
            <h4 class="bi bi-people-fill">メンバー</h4>
            <% @group.users.each do |user| %>
              <p class="border-bottom"><%= user.name %></p>
            <% end %>
          <h4 class="bi bi-cursor-fill">招待</h4>
            <%= form_with(model: :group_user, scope: :post, url: group_group_users_path(@group), local: true) do |f| %>
              <%= f.label :email, class: "bi bi-envelope"  %>
              <%= f.email_field :email, class: "form-control", placeholder: "sample@example.com" %><br>
              <div class="button">
                <%= f.submit '招待する', class: "btn btn-info" %>
              </div><br>
            <% end %> 
          <% if current_user == @group.owner %>
            <%= link_to "グループを編集", edit_group_path(@group), class: "bi bi-pencil-fill btn btn-success btn-sm", id: "edit_group" %>
            <%= link_to "グループを削除", @group, method: :delete, data:{ confirm: "削除しますか？"}, class: "bi bi-trash3-fill btn btn-danger btn-sm" %>
          <% else %>
            <% if @group.users.ids.include?(current_user.id) %>
              <%= link_to "グループから退出", group_group_user_path(@group), method: :delete, data: { confirm: "グループから退出しますか？"}, class: "btn btn-secondary btn-sm" %>
            <% end %>
          <% end %>
          <br><br>
          <%= link_to "戻る", user_path(current_user.id), id: "back", class: "bi bi-skip-backward-fill btn btn-sm btn-primary" %>
        </div>
      </div>  
    </div>
  </div>
</div>
 

  

app/views/labels/edit.html.erb
<%= form_with(model: @label, local: true) do |form| %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8">
      <div class="card">
        <div class="card-body"> 
          <h2 class="bi bi-tag-fill">カテゴリ編集</h2>
            <% if @label.errors.any? %>
              <div id="error_explanation">
                <h4><%= pluralize(@label.errors.count, "件の") %> エラーがあります</h4>
                  <% @label.errors.full_messages.each do |message| %>
                    <%= message %>
                  <% end %>
              </div>
            <% end %>
          <div class="field">
            <%= form.label 'カテゴリ名' %>
            <%= form.text_field :name, class: "form-control" %>
          </div>
          <br>
          <div class="actions">
            <%= form.submit '編集する', class: "btn btn-sm btn-success" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<br>          
<%= link_to t(' 戻る'), labels_path, id: "back", class: "bi bi-skip-backward-fill btn btn-sm btn-primary" %>
<% end %>

app/views/labels/index.html.erb
<div class="container">
  <h1>カテゴリ一覧</h1>
  <br>
  <%= link_to '  カテゴリを登録する', new_label_path, class: "btn btn-primary bi bi-plus-circle-fill" %>
  <br><br>
  <table class = "table">
    <thead class="border-top">
      <tr>
        <th>カテゴリ名</th>
        <th>登録仕込み数</th>
      </tr>
    </thead>
    <tbody>
      <% @labels.each do |label| %>
        <tr>
          <td><%= label.name%></td>
          <td><%= label.food_preps.count %></td>
          <td><%= link_to ' 編集する', edit_label_path(label), class: "bi bi-pencil-fill btn btn-outline-success" %></td>
          <td><%= link_to ' 削除する', label_path(label), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-outline-danger bi bi-trash3-fill" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/labels/new.html.erb
<%= form_with(model: @label, local: true) do |form| %>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-8">
        <div class="card">
          <div class="card-body"> 
            <h2 class="bi bi-tag-fill">カテゴリ作成</h2>
            <% if @label.errors.any? %>
              <div id="error_explanation">
                <h3><%= pluralize(@label.errors.count, "件の") %> エラーがあります</h3>
                  <% @label.errors.full_messages.each do |message| %>
                    <%= message %>
                  <% end %>
              </div>
            <% end %>
            <div class="form-group">
              <%= form.label "カテゴリ名" %>
              <%= form.text_field :name, class: "form-control", placeholder: "肉類" %>
            </div>
            <br>
            <div class="actions">
              <%= form.submit "作成する", class: "btn btn-sm btn-info" %>
            </div>
          </div>
        </div>
      </div>
    </div>        
  </div>
  <% end %>
  <br>
<%= link_to "戻る", labels_path, id: "back", class: "bi bi-skip-backward-fill btn btn-sm btn-primary" %>