config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: "users/sessions",
  }
  root 'top#index'
  resources :users, only: [:index, :show]
  resources :food_preps do
    collection do
      get 'search'
    end
  end  
  resources :labels
  resources :select_food_preps do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end
  resources :groups do
    resources :group_users
  end
  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#guest_sign_in'
    post 'users/admin_guest_sign_in', to: 'users/sessions#admin_guest_sign_in'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/food_prep.rb
class FoodPrep < ApplicationRecord
  validates :name, presence: true
  validates :ingredient, presence: true
  validates :group_id, presence: true
  has_many :food_prep_labels, dependent: :destroy
  has_many :labels, through: :food_prep_labels, source: :label
  has_many :select_food_preps, dependent: :destroy
  belongs_to :group
end

app/controllers/food_preps_controller.rb
class FoodPrepsController < ApplicationController
  before_action :set_food_prep, only: [ :show, :edit, :update, :destroy ]
  before_action :set_search_food_prep, only: [:index, :search]
  
  def index
    @food_preps = FoodPrep.all 
    @group_food_preps = @food_preps.where(group_id: current_user.group_ids)
  end

  def show
  end

  def new
    @food_prep = FoodPrep.new
    @groups = GroupUser.where(user_id: current_user.id)
  end

  def edit
  end

  def create
    @food_prep = FoodPrep.new(food_prep_params)
    if @food_prep.save
      redirect_to food_preps_path, notice: '仕込みを登録しました'
    else
      @groups = GroupUser.where(user_id: current_user.id)
      render :new, notice: '仕込みの作成に失敗しました'
    end
  end  

  def update
    if @food_prep.update(food_prep_params)
      redirect_to food_preps_path, notice: '仕込みを編集しました'
    else
      render :edit
    end
  end

  def destroy
    @food_prep.destroy
    redirect_to food_preps_path, notice: '仕込みを削除しました'
  end

  def search
    @results = @search_food_prep.result.where(group_id: current_user.group_ids)
  end

  private

  def set_food_prep
    @food_prep = FoodPrep.find(params[:id])
  end

  def food_prep_params
    params.require(:food_prep).permit(:name, :ingredient, { label_ids: [] }, :group_id)
  end

  def set_search_food_prep
    @search_food_prep = FoodPrep.ransack(params[:q])
  end
end

app/helpers/food_preps_helper.rb
module FoodPrepsHelper
end

app/views/food_preps/edit.html.erb
<div class="container">
  <%= form_with(model: @food_prep, local: true) do |form| %>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-10">
          <div class="card">
            <div class="card-body">
              <h2>仕込み内容編集</h2>
                <% if @food_prep.errors.any? %>
                  <div id="error_explanation">
                    <h3><%= pluralize(@food_prep.errors.count, "件の") %> エラーがあります</h3>
                      <% @food_prep.errors.full_messages.each do |message| %>
                        <%= message %><br>
                      <% end %>
                  </div>
                <% end %>
              <br>
              <div class="card">
                <div class="card-body">
                  <div class="form-group">
                    <%= form.label "仕込み項目名" %>
                    <%= form.text_field :name, class: "form-control" %>
                  </div>
                  <br>
                  <div class="form-group">
                    <%= form.label "使用食材" %>
                    <%= form.text_area :ingredient, class: "form-control" %>
                  </div>
                  <br>
                  <div class="form-group">
                      <%= form.label "カテゴリ" %> :
                    <% Label.all.each do |label| %>
                      <%= form.check_box :label_ids, { multiple: true, include_hidden: false }, label[:id] %>
                      <%= label.name %>
                    <% end %>
                  </div>
                </div>
              </div>
              <br>
              <div class="button">
                <%= form.submit '編集する', class: "btn btn-success" %>
              </div>
            </div>
          </div>
        </div>
      </div>        
    </div>
  <br>    
  <% end %>
<%= link_to t('戻る'), food_preps_path(@food_prep), class: "bi bi-skip-backward-fill btn btn-sm btn-primary" %>
</div>

app/views/food_preps/index.html.erb
<div class="container">
<h2 class="bi bi-wallet">登録済仕込み一覧</h2>
  <%= link_to " 新しく仕込みを登録する", new_food_prep_path, class: "bi bi-plus-circle-fill btn btn-primary"%>
  <br><br>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-6">
        <div class="card">
          <div class="card-body">
            <%# 検索フォーム %>
            <h4 class="bi bi-search">仕込み検索</h4>
            <%= search_form_for @search_food_prep, url: search_food_preps_path do |f| %>
              <%= f.label :name_cont, '仕込み項目名' %>
              <div class="form-group">
                <%= f.search_field :name_cont, class: "form-control", placeholder: "例)トマトソース" %>
                <br>
                <%= f.submit '検索', class: "btn btn-info btn-sm" %>
              </div>  
            <% end %>
            <%# 検索フォーム %>
          </div>
        </div>
      </div>
    </div>        
  </div>
  <br>
  <table class = "table">
    <thead>
      <tr class="border-top">
        <th><%= "仕込み項目名" %></th>
        <th><%= "使用食材" %></th>
        <th><%= "カテゴリ" %></th>
      </tr>
    </thead>
    <tbody>
      <% @group_food_preps.each do |food_prep| %>
        <tr>
          <td class="bi bi-chevron-right"><%= food_prep.name %></td>
          <td><%= food_prep.ingredient %></td>
          <td>
            <% food_prep.labels.each do |label| %>
              <%= label.name %>
            <% end %>
          </td>
          <td><%= link_to t(' 詳細を見る'), food_prep_path(food_prep), method: :get, class: "bi bi-file-text-fill btn btn-outline-primary btn-sm" %></td>
          <td><%= link_to t(' 編集する'), edit_food_prep_path(food_prep), method: :get, class: "btn btn-outline-success btn-sm bi bi-pencil-fill" %></td> 
          <td><%= link_to t(' 削除する'), food_prep_path(food_prep), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-outline-danger btn-sm bi bi-trash3-fill" %></td> 
        </tr>
      <% end %> 
    </tbody>  
  </table>
</div>

app/views/food_preps/new.html.erb
<div class="container">
  <%= form_with(model: @food_prep) do |form| %>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-10">
          <div class="card">
            <div class="card-body">
              <h2>仕込み作成</h2>
              <% if @food_prep.errors.any? %>
                <div id="error_explanation">
                  <h4><%= pluralize(@food_prep.errors.count, "件の") %> エラーがあります</h4>
                    <% @food_prep.errors.full_messages.each do |message| %>
                      <%= message %><br>
                    <% end %>
                </div>
              <% end %>
              <br>
              <div class="card">
                <div class="card-body">
                  <div class="form-group">
                    <%= form.label "仕込み項目名" %>
                    <%= form.text_field :name, placeholder: "トマトソース", class: "form-control" %>
                  </div><br>
                  <div class="field">
                    <%= form.label "使用食材" %>
                    <%= form.text_area :ingredient, placeholder: "トマト,玉ねぎ", class: "form-control" %>
                  </div><br>
                  <div class="field">
                    <%= form.label "カテゴリ" %>:
                    <% Label.all.each do |label| %>
                      <%= form.check_box :label_ids, { multiple: true, include_hidden: false }, label[:id] %>
                      <%= label.name %>
                    <% end %>
                  </div><br>
                  <div class="field">
                    <%= form.label "グループ名" %>:
                    <% @groups.each do |group| %>
                      <%= form.check_box :group_id, { multiple: false, include_hidden: false }, group[:group_id] %>
                      <%= group.group.name %>
                    <% end %>
                  </div>
                </div>  
              </div>
              <br>
              <div class="button">
                <%= form.submit "作成する", class: "btn btn-info"  %>
              </div>
            </div>
          </div>
        </div>
      </div>        
    </div>  
  <% end %>
</div>  

app/views/food_preps/search.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <div class="card">
        <div class="card-body">
          <h2>検索結果</h2>
          <table class="table">
            <thead class="border-top">
              <tr>
                <th><%= "仕込み項目名" %></th>
              </tr>
            </thead>
            <tbody>
              <% @results.each do |food_prep| %>
                <tr>
                  <td><%= food_prep.name %></td>
                  <td><%= link_to t('詳細を見る'), food_prep_path(food_prep), method: :get, class: "btn btn-outline-primary btn-sm" %></td>
                  <td><%= link_to t('編集する'), edit_food_prep_path(food_prep), method: :get, class: "btn btn-outline-success btn-sm" %></td> 
                  <td><%= link_to t('削除する'), food_prep_path(food_prep), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-outline-danger btn-sm"  %></td> 
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>        
</div>
<br>
<%= link_to t('戻る'), food_preps_path(@results), class: "bi bi-skip-backward-fill btn btn-primary btn-sm"  %>

app/views/food_preps/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-8">
      <div class="card">
        <div class="card-body border border-dark">
          <h2 class="bi bi-info-circle"><%= '仕込み詳細ページ' %></h2>
          <br>
            <div class="card">
              <div class="card-body">
                <p class="border-bottom">
                  <strong><%= '仕込み項目名' %>:</strong>
                  <%= @food_prep.name %>
                </p>
                <p class="border-bottom">
                  <strong><%= '使用食材' %>:</strong>
                  <%= @food_prep.ingredient %>
                </p>
                <p class="border-bottom">
                  <strong><%= "カテゴリ" %>:</strong>
                  <% @food_prep.labels.each do |label| %>
                    <%= label.name %>
                  <% end %>
                </p>
                <%= link_to t('編集する'), edit_food_prep_path(@food_prep), class: "btn btn-success btn-sm  bi bi-pencil-fill" %>
                <%= link_to t('削除する'), food_prep_path(@food_prep), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-danger btn-sm bi bi-trash3-fill" %>
            </div>  
          </div>  
        </div>
      </div>
    </div>
  </div>        
</div>
<br>
<%= link_to t('戻る'), food_preps_path(@food_prep), class: "bi bi-skip-backward-fill btn btn-sm btn-primary"  %>